### ISSUE TITLE
Question about Specs

### ISSUE THREAD

**Issue by idanam-del** [ivlovric/HFP#12]
Hey, I would like to ask

- what's the buffer size? can it be configurable?
- When HEP Server is unavailable how much times the HFP retry the connection and at what interval?
- After flushing - On homer would i see the call with the captured date or when it was flushed?

**Comment by ivlovric** [comment]
Hi!

Buffer size internally is set to max tcp window size just to make sure we dont miss anything, although it will never hit that limit and it is not configurable. We are making sure we catch everything to file - https://github.com/ivlovric/HFP/blob/main/HFP.go#L134

When HEP server is unavailable HFP will try indefinitely every 5 seconds

Capture date is luckily encoded and transmitted in HEP packet itself by its origin encoder, so when flushed it should be preserved in the end.

I

**Comment by idanam-del** [comment]
Thank you for answering my questions

But  65535 bytes limit is enough? the default buffer size on [heplify](https://github.com/sipcapture/heplify) is 32MB.  65535 bytes are 0.52428 megabit.

  -b int
	Interface buffersize (MB) (default 32)

**Comment by ivlovric** [comment]
Hi,

buffer limit is enough, it is tcp buffer which by design cant be any higher. heplify is seemingly buffering on some other level higher than tcp - interface level which is os abstraction. 
Feel free to try "-d on" switch on HFP, there is more info on packets received in bytes in relation to **tcp** buffer size.
